### PR TITLE
Support Boot options

### PR DESCRIPTION
**Pull request by IslandUsurper**
Only supports reading and setting boot flags (parameter 5 in Table 28 of the spec), but it will be fairly easy to add functions for other boot option parameters.

### CODE REVIEW

**Comment by IslandUsurper** [comment]
Oh wait. I need to add a couple of API functions to eipmi.erl.

**Comment by schlagert** [comment]
Thank you, for your contribution/effort. I'll try to have a look into this today.

**Comment by IslandUsurper** [comment]
Friendly reminder for review.

**Comment by schlagert** [comment]
Thanks for the reminder! Totally forgot about this PR :scream: Looking into it now...

**Pull request merged**
